remove dependency on jinja
It turns out that we don't actually use the jinja framework, at least
not since commit 74894ad which somewhat brutally removed the dummy
views/*.j2 files. For some reason it still used to work, but now
apparently some change in jinja makes us fail with

  ValueError: The 'powerrelay' package was not installed in a way that PackageLoader understands.

Getting one less dependency is nice.